---
apiVersion: v1
kind: Deployment
metadata:
  name: node-app
  namespace: ns-github-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-image
          image: acrtestaksapp.azurecr.io/suresh342/node-app:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
          ports: 
            - containerPort: 8080
          livenessProbe:
           tcpSocket:
            port: 8080
          readinessProbe:
           tcpSocket:
            port: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: ns-github-app
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080





          








